project1: PasswordCrack.o TrieDictionary.o
	g++ -g -Wall -std=c++11 -o project1 PasswordCrack.o TrieDictionary.o
PasswordCrack.o: PasswordCrack.c++
	g++ -g -Wall -std=c++11 -c PasswordCrack.c++
TrieDictionary.o: TrieDictionary.c++
	g++ -g -Wall -std=c++11 -c TrieDictionary.c++
clean:
	rm *.o project1
